### ISSUE TITLE
Run nnunet on LSF(IBM)

### ISSUE THREAD

**Issue by ruiyangqin2016** [MIC-DKFZ/nnUNet#893] opened 2021-12-23 03:55 UTC
Hi,

My lab hope to train the model based on LSF. Basically, I login to cluster use ssh, but the lab computer which interacts with me is a normal computer. I use bsub < *name*.sh to submit jobs into the clusters. 

Here is my question. I install nnunet in the lab computer which interacts with me, and I am just trying to apply gpu from the clusters to train my model. But each time I submit jobs, the output file shows that it doesn't recognize "nnunet". Do I need to install nnunet and deploy variable environments on the cluster?

My apologies that this question may not be closely related to nnunet itself, but I believe it's valuable since maybe there are more labs are doing the same thing.

Thank you!

**Comment by FabianIsensee** [comment] 2021-12-23 05:58
duplicate of #894

**Closed** 2021-12-23 05:58 UTC
