### ISSUE TITLE
One or more background workers are no longer alive

### ISSUE THREAD

**Issue by hdnminh** [MIC-DKFZ/nnUNet#1887] opened 2024-01-11 08:49 UTC
Hi @FabianIsensee 

I have this error when running: 
raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the "
RuntimeError: **One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message**

```bash
!OMP_NUM_THREADS=1 nnunet_proc_DA=0 nnUNet_train 2d nnUNetTrainerV2 124 0 --npz
```

**My system:**
- NVIDIA GeForce GTX 1080 Ti: 12GB
- Memory: 32GB

Do you have any idea to solve this problem? Cause I need to run on nnUNet v1, can you tell me what exactly this error is? And how can I manually fix it?

**Comment by hdnminh** [comment] 2024-01-11 13:46
Hi @FabianIsensee 

Whenever you're free, please help me. Thank you so much.

**Comment by hdnminh** [comment] 2024-01-18 05:36
Hi @FabianIsensee,

Can you help me?

**Comment by FabianIsensee** [comment] 2024-01-18 08:50
Hey, sorry for the delay.
Please read the error message carefully. It asks you to `check the print statements above for the actual error message`. Have to taken a look at that? What does it say?
Maybe just share the entire text output with us, that makes things easier

**Comment by hdnminh** [comment] 2024-01-26 06:34
Hi @FabianIsensee 

This is the text output:

```
/media/lhbac02/model/nnunet_ext/evaluation/evaluator.py:324: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop

```

**Comment by FabianIsensee** [comment] 2024-01-26 16:35
It looks like you are still using V1. Have you considered moving to V2? We no longer develop V1 :sweat_smile: 

From the pasted text it still is not clear what the problem is. Can you please share everything, from the start of the training to the crash?

**Comment by hdnminh** [comment] 2024-01-27 17:29
Because I am using a variant of nnUNet, that is lifelong nnUNet (https://github.com/MECLabTUDA/Lifelong-nnUNet/tree/main) , so that why I must use nnUNet v1.

This is completely output error:
```
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:220: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  model_sum = model_sum.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:244: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  model_sum = model_sum.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 980, in _bootstrap_inner
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
    self.run()
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 917, in run
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop

```

I do appreciate your time. Thank you so much, @FabianIsensee <3

**Comment by hdnminh** [comment] 2024-01-27 17:32
```
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:220: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  model_sum = model_sum.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:244: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  model_sum = model_sum.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
/media/lhbac02/Context-Based-Continual-Learning/nnunet_ext/evaluation/evaluator.py:332: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  summary = summary.append(row_series, ignore_index=True)
Exception in thread Thread-20:
Traceback (most recent call last):
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message
Exception in thread Thread-19:
Traceback (most recent call last):
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/media/lhbac02/miniconda3/envs/cuda117/lib/python3.9/site-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 92, in results_loop
    raise RuntimeError("One or more background workers are no longer alive. Exiting. Please check the print"
RuntimeError: One or more background workers are no longer alive. Exiting. Please check the print statements above for the actual error message

```

**Comment by FabianIsensee** [comment] 2024-01-30 09:26
Hey, as much as I would like to help I am still at a loss. There is no proper error message in those prints even though there should be. Are you running this on a batch cluster? If so error messages sometimes get moved around in the text output that one is receiving. Can you please check the entire thing if there is something we missed?
One thing to try would be to get rid of the futurewarning by downgrading pandas. Or ask the lifelong nnU-Net people if they know what is going on

**Comment by hdnminh** [comment] 2024-02-01 16:05
Hi @FabianIsensee,

Thank you for your reply & recommendation.

I tried to fix some code to work with a new version of pandas and **remove** the **warning** about **future** **pandas**. Then all the **code** **runs** unexpectedly **successfully**.

Yes, I **use** a b**atch cluster** to train model. **Despite of the success**, I have some **warnings** in **.err** file (all of content in .err file below):
```
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
OMP: Warning #191: Forking a process while a parallel region is active is potentially unsafe.
```

Have you met any warnings before? And Is it safe?

**Comment by FabianIsensee** [comment] 2024-02-02 07:23
I have never seen those warnings. I can't say whether that is safe or not

**Closed** 2024-02-04 07:12 UTC
