### ISSUE TITLE
docker crash on 3d training/inference

### ISSUE THREAD

**Issue by bkonk** [MIC-DKFZ/nnUNet#527] opened 2021-02-19 21:30 UTC
I've been training and running inference with nnunet successfully for a few months but after some recent improvements to our server, 3d models crash the docker container right after training or inference begins. 

Our recent upgrade included installation of new RAM/CPU, updated nvidia drivers, and install of nvidia-runtime-patch. Our server is running a GeForce RTX 2080 Ti, equipped with cuda v 11.2, driver 460.32.03. I've tried using the fabianisensee/isen2020 image, and running with:
`docker run --gpus all —name ds_nnunet -it --ipc=host --shm-size=10g -v /mnt/Data:/DataMount fabianisensee/isen2020 /bin/sh`
I add `export OMP_NUM_THREADS=1` to my bashrc along with  nnUNet_raw_data_base, etc. paths. 

2d models seem to run fine within this container, but 3d inference leads to a crash before any .gz result files are generated (pkl file is generated) and training similarly crashes right away. I've tried using a few nnunets that I've trained over the last few months on different datasets and hit the same crash issue.

I've also spun up the same job within a virtualenv on the same machine and can run 3d there without issue...so seems like a docker-specific issue. Do you have any troubleshooting suggestions?

**Comment by Scotchman0** [comment] 2021-02-19 21:49
Hello! Just chipping in to update that I work with @bkonk and can also provide data for this issue. I've attached a hardware print in a few attached txt files for diagnostic purposes and replication. However because it' will become relevant:

We have reinstalled Nvidia Drivers, we have reinstalled Docker, we have reinstalled cuda.

The system is running 2 Xeon cores, 180G RAM, and a GeForce RTX 2080 

We have a separate system, running 2 Xeon cores (same) 180G ram (same) and a GeForce RTX 2080 and 3090 card (not sequenced). This secondary system is set up very similarly and exhibits the exact same problem in Docker.

[lscpu.txt](https://github.com/MIC-DKFZ/nnUNet/files/6013088/lscpu.txt)


docker version
Client: Docker Engine - Community
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:13 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

docker environment pip freeze attached. 
[freeze_stuffs.txt](https://github.com/MIC-DKFZ/nnUNet/files/6013010/freeze_stuffs.txt)

When we say crash, we mean full system reset, the entire computer shuts down hard after a system hang when the 3d modeling spins up.

We have attempted to limit the process to a single Core (no change) we have attempted to limit the process to a single CPU (--cpuset-cpu=0-19) - (no change). We have attempted to boost the memory based on previous threads here with the flag: 
--ipc=host --> no change.

We run into an issue when we boot these containers or run sudo docker run -it --rm --gpus all ubuntu nvidia-smi to check nvidia communications: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]

which is resolved after installing: nvidia-container-toolkit. My gut says this is related somehow but since it doesn't interfere with the virtualenv processing, i'm not sure.

Other relevant data: CPU stress on all cores has been completed, no issues, GPU stress with maximum output has been completed as well, no issues. The system is more than capable of handling the workload, and when the issue appears, we're not even past 15% utilization on CPU pressure - maybe 4 cores in use (out of 40) if not constrained to a single core.

No power issues otherwise and the system can run stress tests inside docker containers without issue. 

Need a fresh set of eyes on this - happy to gather whatever data is needed to assist. (Thanks in advance for your time, and also for publishing this very useful system).
~Will

----------

**Comment by FabianIsensee** [comment] 2021-02-22 08:16
Hey there, 
the docker you reference is our brats 2020 docker. It is not meant to be used for anything other than running the brats inference.

If your whole server crashed when running it then something is very wrong with the server. I do not know what it is - but that code runs just fine for others and it did run fine for you as well. So something must be off with either your OS/driver or hardware.

I am sorry I cannot be more helpful.

Best,
Fabian

**Comment by FabianIsensee** [comment] 2021-02-22 08:16
have you checked GPU and CPU temperature?

**Comment by Scotchman0** [comment] 2021-02-22 14:51
Hey Fabian, 

We have confirmed that the GPU and CPU temps are no where near critical levels when the crash happens - cooling is fine, and under load we are able to increase temps significantly without crash on these systems. 

I re-read my addendum and I realized I didn't specify that this issue ONLY happens when the code is run in Docker, and if we run it in a virtualEnv, it renders with no problem. I'll do some more digging today and if I figure it out I'll reply to the thread with the solution - but it is strange.

I can't understand what's different about our container and the virtualenv, and the fact that it happens the same way on two separate pieces of hardware is concerning. We'll try and replicate the issue with another 3d modeling applet and see if we can disentangle from this code-base being the common thread.

~Will

**Comment by FabianIsensee** [comment] 2021-02-23 07:27
Hi Will,
I really don't know how to help you. If the code runs in a regular environment nothing is wrong with it (and I don't see how this could cause this kind of problems!). There must be something else going on and I am in no way qualified to solve this :-/
Best,
Fabian

**Comment by FabianIsensee** [comment] 2021-02-23 08:25
(maybe try upgrading the linux kernel)

**Comment by Scotchman0** [comment] 2021-03-03 23:43
Hey Fabian,

Updating to advise you can close this issue - we have discovered that much to our dismay, we had TWO separate problems that resulted in the same behavior, that were compounding our issue. 1. We had a power distribution issue on one of our two systems, and it would appear that limiting our power throughput to the GPUS has prevented the internal power supply from reading high spikes as 'problematic over-drafting of power' and it considers it stable enough to stay on. We limited the power supply to 350W on the 3090 GPU from 370 and that seems to have done the trick. on the OTHER machine, however, we simply have what appears to be a faulty card, and spinning up the GPU with any real intensity causes an outage. We didn't catch this, because of course we were considering this system our baseline for testing (50/50 picked one and ran with it, turns out it's the borked one).

If you're from the future and wondering what did we do to test, I'm documenting here the solutions that led us to our finding and subsequent (pending) RMA of the bad GPU:


Limit power usage
sudo nvidia-smi --persistence-mode=1
sudo nvidia-smi --power-limit=350

Ran a power feed monitor with: 
$ nvidia-smi --loop-ms=20 --format=csv,noheader,nounits --query-gpu=power.draw > out.txt
$ tail -f out.txt 
ran the tail in a separate shell to watch for huge spikes and review log after crash - saw that we were getting spikes into the 400's easily which were probably tripping the power supply on the now-slightly-limited machine that is cooperating.

and of course, we upgraded kernel, reinstalled NVIDIA drivers (tried earlier versions but 3090 needs latest), and reinstalled docker/cuda etc. --> these didn't help but I'm very good at refreshing all of these after doing it about 3X on both systems now so that's good.

also checked heat output on CPU/GPUs etc.

Anyway all the best and thanks very much for your time.

~Will

**Comment by FabianIsensee** [comment] 2021-03-04 10:10
Thanks for the update! Indeed, 3090 GPUs can suck upwards of (I believe) 500W for a couple of ms, so you really need to have a beefy PSU for those in order to not trigger overcurrent protection. That is a rather widely known issue with these cards in the PC gaming community. It is interesting that whoever designed your sever didn't think about that. Limiting the power of the GPU is a great idea but it of course will also come at the cost of reduced performance. Maybe it will be worth spending a little extra on an upgraded PSU?
Best,
Fabian

**Comment by Scotchman0** [comment] 2021-03-04 14:14
We've got a 1400W psu which is the part that is most confusing - it SHOULD be able to handle (and it does) when not spiking to 500W periodically - but even under load, the system is still not maxed out. Something about limiting those 20W means the high caps are slightly lower and don't trip the safeties. It's super weird. We're gonna keep poking at it internally and see if we can't figure out anything better. Good news though is that even limited to 350W cap, we're averaging 320W while it's under load, coupled with the 250W cap of the other card... we're only pushing maybe 1200W of our 1400W ceiling.

¯\_(ツ)_/¯

**Comment by FabianIsensee** [comment] 2021-03-04 16:40
Well if you already push 1200/1400W then you don't have a lot of headroom. One spike and that's it.
Also you should not forget that some PSUs can only deliver a given amount of power per 6/8 pin connector (depends on how the 12V rails are wired internally) so the rail that is connected to the GPU may run into overcurrent even though the rest of the system seems fine.
Best,
Fabian

**Comment by Scotchman0** [comment] 2021-03-04 17:07
Good point there 🤔

**Comment by Scotchman0** [comment] 2021-03-04 20:20
Bad GPU confirmed - The MSI card just can't handle any load even when stripped way down. it's getting RMA'd. the ZOTAC card we have (also a 3090) works great in either machine. Thanks for going on a ride with us.

**Comment by FabianIsensee** [comment] 2021-03-05 10:07
Thank you for sharing. It's always a learning experience and since I am interested in hardware stuff anyways I don't mind discussing that at all. If it wasn't for you I would never have thought of overcurrent protection as cause of the problem you were having (even though it seems rather obvious in hindsight). So that's something new I can take home :-)
Best,
Fabian

**Comment by Scotchman0** [comment] 2021-04-19 12:25
Hello all from the future. Looping back around to this issue - I wanted to provide additional context to anyone else who stumbles upon this thread from google trying to figure out what the hell is wrong with their GPU as well:

https://forums.developer.nvidia.com/t/msi-3090-gpu-causes-a-full-system-crash-when-under-any-sort-of-load-ubuntu-18-04lts/175117/6

You can read my nvidia thread above if you care to, but the tl;dr version is:

We RMA'd the card, it came back (MSI advised that we should install windows and test it). We discovered ulimately that the bottom rail on the P920 workstation we're using has a wattage cap that is lower than the MSI 3090 GPU. When we bridged in power from the top rail also, the card runs fine. The difference in max cap wattage is about 20W compared to the Zotac card we were using that capped at 350, the MSI caps at 370 (which is more than the bottom rail wants to grant). 

Anyway, hope this helps some people out there figure out what's up with the chip. This is the 3090 MSI Gaming Trio card. The PSU can absolutely support the load, just can't do it only balancing the pull through the bottom rail pin cables only. The more you know.

Cheers.
~Will

**Comment by FabianIsensee** [comment] 2021-04-28 10:25
Thanks @Scotchman0 !

**Closed by FabianIsensee** 2021-04-28 10:25 UTC
