### ISSUE TITLE
Could not find a task with the ID %d

### ISSUE THREAD

**Issue by lordhjx** [MIC-DKFZ/nnUNet#2108] opened 2024-04-18 05:09 UTC
Hello, I want to generate the json file by using nnUNet_plan_and_preprocess, and I used the command 
./nnUNet_plan_and_preprocess -t 012
and it shows:
**raise RuntimeError("Could not find a task with the ID %d. Make sure the requested task ID exists and that "
RuntimeError: Could not find a task with the ID 12. Make sure the requested task ID exists and that nnU-Net knows where raw and preprocessed data are located (see Documentation - Installation). Here are your currently defined folders:
nnUNet_preprocessed=C:\Users\25384\Desktop\nnUNet_preprpcessed
RESULTS_FOLDER=C:\Users\25384\Desktop\nnUnet_results
nnUNet_raw_data_base=C:\Users\25384\Desktop\nnUNet_raw
If something is not right, adapt your environemnt variables.**
I am pretty sure the environment variables are set correctly and this is where I put my raw data: "C:\Users\25384\Desktop\nnUNet_raw\Dataset012_Heart"
Can you help me figure out what happened?

**Comment by lordhjx** [comment] 2024-04-18 11:38
Do I need to turn all the imagesTr names into format like {id}_0000.nii.gz?

**Comment by TaWald** [comment] 2024-04-20 15:11
Seems like your path is not correctly set?
`nnUNet_preprpcessed` sounds like a typo and you misstyped and `o` for a `p`. Or did you deliberately set it to prepr**p**cessed?

**Comment by lordhjx** [comment] 2024-04-21 18:02
Yes I found that problem and fix it, but it still can't find my dataset folder.

**Comment by TaWald** [comment] 2024-04-22 14:59
I guess some more information would be helpful:
1. Which OS are you using?
2. Which nnU-Net version are you using?
3. Can you provide a screenshot of a `ls` equivalent in `C:\Users\25384\Desktop\nnUNet_raw` to show what the directory contains. (Make sure you go to the right directory (`C:\Users\25384\Desktop\nnUNet_raw`)

Generally Your error should only occur if the dataset does indeed not exist in the directory, so you must be either A) Messing  something up in the scope of naming the directory or B) Messing something up with the path to the directory. |

You also HAVE to make sure that the files are named as `{id}_0000.nii.gz` (the .nii.gz could also be some other 3D image ending like .nrrd) in order for nnU-Net to work correctly.

**Comment by lordhjx** [comment] 2024-04-23 07:43
Windows 11. nnU-Net V2.
<img width="1270" alt="屏幕截图 2024-04-23 154135" src="https://github.com/MIC-DKFZ/nnUNet/assets/104721210/13ce4a5d-f0e0-46f3-8701-c5a1ce0e3826">
<img width="1280" alt="屏幕截图 2024-04-23 154052" src="https://github.com/MIC-DKFZ/nnUNet/assets/104721210/95718693-89f4-4b98-8fa3-840aa91a58ea">
The other 2 folders are generated automatically

**Comment by TaWald** [comment] 2024-04-23 18:05
The issue is that you are running **nnunetv1** and not **nnunetv2** -- The term **Task** was only used in v1, and is now replaced by dataset -- If you want to verify you can check the supposed print-out [here](https://github.com/MIC-DKFZ/nnUNet/blob/3808231601265aed98d70de4218fc845e185959d/nnunetv2/utilities/dataset_name_id_conversion.py#L48).

If you have both nnunet versions you should just call `nnUNetv2_plan_and_preprocess` with the dataset ids instead and everything should work fine.

In general it would be nice if you would next time also provide the entire stacktrace and not just the error message, because it includes in which function the error is raised. This would likely improve time till solving of the issues you pose in the future :) 

If you should not have nnunetv2 installed yet you can follow this [official guide](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/installation_instructions.md). If there should be more issues, please let me know and when this helped you resolve the issue feel free to close this issue. :v:

**Comment by lordhjx** [comment] 2024-04-23 18:08
Ok Thank you very much! :)

**Closed** 2024-04-25 09:05 UTC
