### ISSUE TITLE
Cannot install nnUnetv2

### ISSUE THREAD

**Issue by akeebatra** [MIC-DKFZ/nnUNet#1534] opened 2023-06-29 22:06 UTC
Hi, I am trying to install nnUnetv2 in virtual environment on a power p8 pc. I am getting following error and can't understand what's going on. Any help will be highly appreciated!

<img width="1268" alt="image" src="https://github.com/MIC-DKFZ/nnUNet/assets/107375551/710913e5-8e78-49f0-8f6d-343ba075ebbc">

**Comment by ancestor-mithril** [comment] 2023-06-30 08:03
This looks like an error caused by scikit-image and is related to numpy. 
Try ensuring that scikit-image is already installed before installing nnUNet. If it does not work, ask on the scikit-image github.

**Comment by GregorKoehler** [comment] 2023-08-02 17:55
Hi @akeebatra,
did the answer provided by @ancestor-mithril resolve your issue? If so, please let us know so we can close this issue. If you're still encountering issues with the install, please let us know!

**Closed** 2023-08-14 09:25 UTC
