### ISSUE TITLE
Error during the running of evaluation

### ISSUE THREAD

**Issue by parvezamu** [MIC-DKFZ/nnUNet#66] opened 2019-09-16 14:11 UTC
Dear Isensee,
I faced this error..........during the execution of this command..............
python evaluation/model_selection/figure_out_what_to_submit.py -m 3d_lowres 3d_fullres -t 43...
I have attached the error...........I trained only two models, each for five-folds .............
The  paths in paths.py are:
1. base = "/home/parvezamu/pytorch"
2.  preprocessing_output_dir = "/home/parvezamu/pytorch/folder_with_preprocessed_data"
3. network_training_output_dir = "/home/parvezamu/pytorch/folder_with_results"

These are folders which were created during the pre-processing and training :
parvezamu@node22:~/pytorch$ ls
folder_with_preprocessed_data  folder_with_results  nnUNet_raw  nnUNet_raw_cropped  nnUNet_raw_splitted
I have attached sub-folders of all the folders. These are:
1.  folder_with_preprocessed_data
parvezamu@node22:~/pytorch/folder_with_preprocessed_data/Task43_BraTS2019$ ls
dataset.json  dataset_properties.pkl  gt_segmentations  nnUNet_2D_stage0  nnUNetPlans_plans_2D.pkl  nnUNetPlans_plans_3D.pkl  nnUNet_stage0  splits_final.pkl
2. folder_with_results
3d_lowres 3d_fullres
In both of these folders, inside validation there is a summary.json
3. nnUNet_raw
Task43_BraTS2019 After enter in
imagesTr  labelsTr
4. nnUNet_raw_cropped
Task43_BraTS2019 After enter in
dataset.json                HGG__BraTS19_2013_17_1.pkl  HGG__BraTS19_2013_23_1.pkl  HGG__BraTS19_2013_7_1.pkl   LGG__BraTS19_2013_29_1.npz 
I have show only few
5. nnUNet_raw_splitted
HGG  LGG  Task43_BraTS2019
Inside Task43_BraTS2019
dataset.json  imagesTr  labelsTr
As per your instructions, this is training command
python run/run_training.py 3d_fullres nnUNetTrainer Task43_BraTS2019 0 --ndet

![image](https://user-images.githubusercontent.com/23691260/64965006-c581ee00-d8ce-11e9-8672-1779ccda1452.JPG)

**Comment by FabianIsensee** [comment] 2019-09-17 07:55
Hi,
thanks for reporting this issue! There is indeed a problem and I will try to fix this today.
Best,
Fabian

**Comment by parvezamu** [comment] 2019-09-17 13:17
Thanks............

**Comment by FabianIsensee** [comment] 2019-09-17 14:33
Hi,
please run summarize_results_in_one_json.py, followed by figure_out_what_to_submit.py and let me know if it works now. 
Best,
Fabian

**Comment by parvezamu** [comment] 2019-09-17 14:48
Hi,
As per your instructions, I have performed both of the operations of evaluation.............But it seems that.....on print command............out_dir_all_json = join(network_training_output_dir, "summary_jsons").......it returns none..............so still an error.....................
![Capture](https://user-images.githubusercontent.com/23691260/65052550-37286d80-d99d-11e9-95d9-d63f5e5f0d3f.JPG)

**Comment by parvezamu** [comment] 2019-09-17 14:54
Hello,
After running summarize .......I have performed cross-validation on 3d full residual.....................this is the output .............................while under folder-with-results.............fold_0  fold_1  fold_2  fold_3  fold_4  plans.pkl
![Capture](https://user-images.githubusercontent.com/23691260/65053105-06950380-d99e-11e9-828f-3927a13eb504.JPG)

**Comment by parvezamu** [comment] 2019-09-18 02:45
Hi,
This is the output of the evaluation section......For both of the models.....jsons are there...............but I think this "json_files = [i for i in subfiles(out_dir_all_json, suffix=".json", join=True) if i.find("ensemble") == -1]" returns NULL. I have attach an Image of the exceutions of both summarize as well as figure out. 
![Capture](https://user-images.githubusercontent.com/23691260/65103645-712b5b00-da01-11e9-960b-d126068bb472.JPG)

**Comment by parvezamu** [comment] 2019-09-18 02:51
This is the output of the evaluation section......For both of the models.....jsons are there
![Capture](https://user-images.githubusercontent.com/23691260/65103903-455ca500-da02-11e9-8f44-79f4318bc329.JPG)

**Comment by FabianIsensee** [comment] 2019-09-18 08:29
You need to pull my changes first :-)

**Comment by parvezamu** [comment] 2019-09-18 08:39
Thanks,
First I performed summarize followed by figure out..................
['/home/parvezamu/pytorch/folder_with_results/summary_jsons/Task43_BraTS2019__2d__nnUNetTrainer__nnUNetPlans__validation.json', '/home/parvezamu/pytorch/folder_with_results/summary_jsons/Task43_BraTS2019__3d_fullres__nnUNetTrainer__nnUNetPlans__validation.json']
Traceback (most recent call last):
  File "evaluation/model_selection/figure_out_what_to_submit.py", line 62, in <module>
    json_files_task = [i for i in subfiles(out_dir_all_json, prefix="Task%02.0d_" % t) if i.find("ensemble") == -1]
TypeError: %d format: a number is required, not str

**Comment by parvezamu** [comment] 2019-09-18 08:46
Sorry.............I missed that...............I thought that only pip install e . make the changes............thanks a lot for such a great work

**Comment by parvezamu** [comment] 2019-09-18 08:56
One more thing I need to understand..........is it possible to fasten the speed of training....I know that to get results we have to train the models longer.............I started the training with your 3d full residual approx two days ago....................I did not change the number of epochs..............it is still 1000....for each epoch same 250 batches...............up to 323 epochs .....the scores are Val glob dc per class: [0.8035633325229462, 0.6726366710578753, 0.8087403210482439]...........................................

**Comment by FabianIsensee** [comment] 2019-09-18 11:51
Good to hear the problem is resolved. Can I close this issue?
Best,
Fabian

**Comment by parvezamu** [comment] 2019-09-18 14:46
Thanks a lot....Yes and again thanks

**Closed** 2019-09-18 14:47 UTC
