### ISSUE TITLE
Minor error in the documentation for "pretraining_and_finetuning" ?

### ISSUE THREAD

**Issue by ValDelch** [MIC-DKFZ/nnUNet#1477] opened 2023-05-31 14:14 UTC
Hi,

I am currently looking at performing pretraining with nnUNet, and I think there is a minor confusion in the documentation (I had to do some modifications to make it run properly). I think this is due to a confusion in the meaning of the source and target terms.

At the begining, the source dataset is defined as the dataset used for pretraining, and the target dataset is the final one, on which fine tuning is performed.
However, if I understand correctly, the source and target terms for the nnUNetv2_move_plans_between_datasets utility have a different meaning. Instead of performing:

```bash
nnUNetv2_move_plans_between_datasets -s SOURCE_DATASET -t TARGET_DATASET -sp SOURCE_PLANS_IDENTIFIER -tp TARGET_PLANS_IDENTIFIER
```

as it is mentioned in the documentation, I had to perform

```bash
nnUNetv2_move_plans_between_datasets -s TARGET_DATASET -t SOURCE_DATASET -sp SOURCE_PLANS_IDENTIFIER -tp TARGET_PLANS_IDENTIFIER
```

in order to properly transfer the plans from the target dataset (final one) to the source dataset (for pretraining).

Furthermore, it seems also important to run a plan_and_preprocess for the source dataset, so that the dataset.json file is generated.

Am I right or am I missing something ?

Cheers!

**Comment by valosekj** [comment] 2023-07-08 13:28
@ValDelch, your issue helped me a lot; thanks!

> I had to perform
> 
> ```shell
> nnUNetv2_move_plans_between_datasets -s TARGET_DATASET -t SOURCE_DATASET -sp SOURCE_PLANS_IDENTIFIER -tp TARGET_PLANS_IDENTIFIER
> ```
> 
> in order to properly transfer the plans from the target dataset (final one) to the source dataset (for pretraining).
> 
> Furthermore, it seems also important to run a plan_and_preprocess for the source dataset, so that the dataset.json file is generated.

I can confirm your observation! As you proposed, I had to run:

```
nnUNetv2_plan_and_preprocess -d SOURCE_DATASET
nnUNetv2_move_plans_between_datasets -s TARGET_DATASET -t SOURCE_DATASET -sp SOURCE_PLANS_IDENTIFIER -tp TARGET_PLANS_IDENTIFIER
```

**Comment by seziegler** [comment] 2023-07-31 14:26
Hi, for pretraining you want to extract the plans from the `TARGET_DATASET` so that you can train on the `SOURCE_DATASET` with the plans from the target you're interested in. So the first command from the docs would be right:
`nnUNetv2_plan_and_preprocess -d TARGET_DATASET`
Afterwards, you want to transfer the plans from the `TARGET_DATASET` to the `SOURCE_DATASET`. I think you're right, that this is confused in the doc. So the next command should be
`nnUNetv2_move_plans_between_datasets -s TARGET_DATASET -t SOURCE_DATASET -sp TARGET_PLANS_IDENTIFIER -tp SOURCE_PLANS_IDENTIFIER`.
@FabianIsensee can you doublecheck and update the [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md#pretraining-on-the-source-dataset)?

**Comment by FabianIsensee** [comment] 2023-08-07 14:55
Thanks guys! It is fixed now

**Closed** 2023-08-07 14:56 UTC

**Comment by chrisrapson** [comment] 2024-02-02 00:06
Looking at the documentation, it currently reads:

https://github.com/MIC-DKFZ/nnUNet/blob/947eafbb9adb5eb06b9171330b4688e006e6f301/documentation/pretraining_and_finetuning.md?plain=1#L41

If I've understood correctly, that means the `-s` flag is associated with the TARGET, and the `-t` flag is associated with the SOURCE. That seems unnecessarily confusing. Wouldn't it be better to swap them?

**Comment by seziegler** [comment] 2024-02-02 16:16
Hi @chrisrapson ,

you've understood correctly. The reason for that is the double meaning of source and target in this context. We have source (pretraining) and target (finetuning) datasets, but we also have the function `nnUNetv2_move_plans_between_datasets` where you move plans from one dataset (arg source) to the other (arg target). Since you want to move the plans from the dataset you want to finetune on (target) to the pretraining dataset (source) you end up with `-s TARGET_DATASET -t SOURCE_DATASET`. I agree that the naming is confusing, but it is correct. We could change the terminology in the doc to pretraining and finetuning dataset to avoid the double meaning... I'll bring it to Fabians attention. Thanks for your suggestion!

Best,
Sebastian

**Comment by YazdanSalimi** [comment] 2024-03-19 13:44
> Dear Fabiban I want to use pretrained models to fine tune them on a new dataset. Unfortunately I have deleted the preprocessed fodlers and raw-data folder, all I have is trained model folders containing the trained models, dataset.json, dataset_fingerprint.json, and plans.json. Could you please let me know if still it is possible to do finetuning and how? Thank you.

this is the error I recive without haing the preprocessed data

 assert isdir(source_folder), f"Cannot move plans because preprocessed directory of source dataset is missing. " \
AssertionError: Cannot move plans because preprocessed directory of source dataset is missing. Run nnUNetv2_plan_and_preprocess for source dataset first!

**Comment by seziegler** [comment] 2024-03-19 14:24
Hi @YazdanSalimi ,
in your case you cannot pretrain your model with the plans of the new dataset. So if you want to use the pretrained model you will need to move the plans from your pretrained model to the new dataset, to make sure that your new dataset will be preprocessed in a similar way as your old dataset was. 
For `nnUNetv2_move_plans_between_datasets` to work, simply create a folder for your old dataset in your nnunet preprocessed directory (as if you still had your preprocessed data) and place the plans file there. Then use the command to move the plans to your new dataset and preprocess it with the plans from your old dataset. After that you can train on your new dataset.

`nnUNetv2_move_plans_between_datasets -s PRETRAINED_DATASET -t NEW_DATASET -sp PRETRAINED_PLANS_IDENTIFIER -tp NEW_DATASET_PLANS_IDENTIFIER`

`nnUNetv2_preprocess -d NEW_DATASET -plans_name NEW_DATASET_PLANS_IDENTIFIER`

`nnUNetv2_train NEW_DATASET CONFIG FOLD -pretrained_weights PATH_TO_CHECKPOINT`

**Comment by YazdanSalimi** [comment] 2024-03-19 14:28
Thank you for your answer. 
It is working now. Thank you. 
Just as a suggestion, what I do when save my trained models, I save a bunch of information about the code generated the model, data loader, batch size, training date, etc with torch.save as a dictionary insiode the model. The trained pth file contains all the information in that case. 
Thak you again for your prompt response.

**Comment by seyidovam** [comment] 2024-08-20 14:17
> Hi, for pretraining you want to extract the plans from the `TARGET_DATASET` so that you can train on the `SOURCE_DATASET` with the plans from the target you're interested in. So the first command from the docs would be right: `nnUNetv2_plan_and_preprocess -d TARGET_DATASET` Afterwards, you want to transfer the plans from the `TARGET_DATASET` to the `SOURCE_DATASET`. I think you're right, that this is confused in the doc. So the next command should be `nnUNetv2_move_plans_between_datasets -s TARGET_DATASET -t SOURCE_DATASET -sp TARGET_PLANS_IDENTIFIER -tp SOURCE_PLANS_IDENTIFIER`. @FabianIsensee can you doublecheck and update the [documentation](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md#pretraining-on-the-source-dataset)?

Dear all, 

I am getting a key error regarding data_identifier while moving plans btw datasets.

I have a separate folders for source and target datasets under both nnunet_raw and nnunet_preprocessed...each datasets has dataset.json files, nnUNetPlans.json files etc...I also compared the structures and content of the nnUNetPlans.json for both source and target datasets. Everything looks correct. I can not understand why I am getting this error. Any help would be greatly appreciated. Thank you very much in advance!



(nnunet_v2) seyidovam@l-radds-gpu-p:~$ nnUNetv2_move_plans_between_datasets -s 052 -t 050 -sp nnUNetPlans_BC -tp nnUNetPlans
Traceback (most recent call last):
  File "/opt/anaconda/anaconda3/envs/nnunet_v2/bin/nnUNetv2_move_plans_between_datasets", line 8, in <module>
    sys.exit(entry_point_move_plans_between_datasets())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda/anaconda3/envs/nnunet_v2/lib/python3.11/site-packages/nnunetv2/experiment_planning/plans_for_pretraining/move_plans_between_datasets.py", line 75, in entry_point_move_plans_between_datasets
    move_plans_between_datasets(args.s, args.t, args.sp, args.tp)
  File "/opt/anaconda/anaconda3/envs/nnunet_v2/lib/python3.11/site-packages/nnunetv2/experiment_planning/plans_for_pretraining/move_plans_between_datasets.py", line 37, in move_plans_between_datasets
    old_identifier = source_plans['configurations'][c]["data_identifier"]
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'data_identifier'
(nnunet_v2) seyidovam@l-radds-gpu-p:~$

**Comment by seziegler** [comment] 2024-08-20 14:23
Hi, can you try running it without the zero in front of your dataset ids? `-s 52 -t 50`

**Comment by seyidovam** [comment] 2024-08-20 15:14
> Hi, can you try running it without the zero in front of your dataset ids? `-s 52 -t 50`

Many thanks for your quick reply... Unfortunately it does not solve the problem. I confirmed that the dataset IDs are correct because "nnUNetv2_plan_and_preproces" command works for both without any problem.

**Comment by seziegler** [comment] 2024-08-21 07:42
Hi, can you please update to the latest version and try again?
In the current version the `data_identifier` key is only loaded if it is contained in the keys.
You can check [here](https://github.com/MIC-DKFZ/nnUNet/blob/9cd9d80ab3d9542138422f33154ee58421a92088/nnunetv2/experiment_planning/plans_for_pretraining/move_plans_between_datasets.py#L38).

**Comment by seyidovam** [comment] 2024-08-28 08:06
Von: Sebastian Ziegler ***@***.***>
Gesendet: Mittwoch, 21. August 2024 09:43
An: MIC-DKFZ/nnUNet ***@***.***>
Cc: Maleyka Seyidova ***@***.***>; Comment ***@***.***>
Betreff: Re: [MIC-DKFZ/nnUNet] Minor error in the documentation for "pretraining_and_finetuning" ? (Issue #1477)


Hi, can you please update to the latest version and try again?
In the current version the data_identifier key is only loaded if it is contained in the keys.
You can check here<https://github.com/MIC-DKFZ/nnUNet/blob/9cd9d80ab3d9542138422f33154ee58421a92088/nnunetv2/experiment_planning/plans_for_pretraining/move_plans_between_datasets.py#L38>.

**Comment by seyidovam** [comment] 2024-08-28 08:27
> Hi, can you please update to the latest version and try again? In the current version the `data_identifier` key is only loaded if it is contained in the keys. You can check [here](https://github.com/MIC-DKFZ/nnUNet/blob/9cd9d80ab3d9542138422f33154ee58421a92088/nnunetv2/experiment_planning/plans_for_pretraining/move_plans_between_datasets.py#L38).

Hi again, 

thank you for your timely replies, I highly appreacite it. Since it is a server without internet access, updating was tedious, I did not do that. But I resolved the issue as following:

 When I kept plan names and json file names for both datasets:  "plans_name": "nnUNetPlans" in nnUNetPlans.json file for both pretraining and target datasets, the following command worked :

 # nnUNetv2_move_plans_between_datasets -s 052 -t 050 -sp nnUNetPlans -tp nnUNetPlans

next command is preprocessing, which worked as well:

#nnUNetv2_preprocess -d 050 -plans_name nnUNetPlans
 
 
 now, I have an issue in training: 
 I started training  2D model with the transferred plans with the following command
 
#nnUNetv2_train 050 2d all -p nnUNetPlans -num_gpus 7


seems training is running since 2 days, nvidia-smi shows gpus are in use, but except training_log file no file is created yet.

**Comment by seziegler** [comment] 2024-08-28 08:39
Hi  @seyidovam ,
you can check [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#using-multiple-gpus-for-training) for documentation on multiple GPUs. I'm not sure what's causing your problem but I would first try running it on only one GPU to see if that might cause the issue.

**Comment by seyidovam** [comment] 2024-08-28 08:49
> Hi @seyidovam , you can check [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/how_to_use_nnunet.md#using-multiple-gpus-for-training) for documentation on multiple GPUs. I'm not sure what's causing your problem but I would first try running it on only one GPU to see if that might cause the issue.

Thank you, working!

**Comment by seyidovam** [comment] 2024-09-03 09:24
Dear @seziegler,

Many thanks for you great replies and support!

I am currently facing cpu load reaching 100% and stops the training process. I could not find anything regarding limiting cpu load during the training in the documentation. I know there are some other options like intsalling limitcpu etc. I wonder if documentation has anything about it?



Thanks in advance!

Best,
Maleyka

**Comment by seziegler** [comment] 2024-09-13 12:19
Hi,
that's rather unusual. In what part of the training does it happen and do you get an error message? How do you check you cpu load?

**Comment by seyidovam** [comment] 2024-09-24 18:22
Thank you very much! 


I am  almost in the final step and need your help with it. I do transfer learning and I am in inference part.
 


Question:

I wonder if "find best configuration" option is possible in Transfer learning at all? 
When I run the command, 

nnUNetv2_find_best_configuration -d 053 -f all -tr nnUNetTrainer --plans nnUNetPlans

it requires the data in folds (but in transfer learning we use all data at once for training), so command does not work for me. 


Your help is highly appreciated!

Many thanks!

Best,
Maleyka

**Comment by seziegler** [comment] 2024-09-25 08:17
Hi Maleyka,

right, on the pretrained data you only run on "all", so you don't have multiple folds. But once you're using the pretrained model for finetuning the dataset, that you're actually interested in, you can train on the individual folds again. So you still need to do the finetuning as described [here](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/pretraining_and_finetuning.md#using-pretrained-weights)

Best,
Sebastian
