### ISSUE TITLE
The crop in preprocess not working

### ISSUE THREAD

**Issue by IrisTT** [MIC-DKFZ/nnUNet#644] opened 2021-05-25 07:50 UTC
Thanks for your code, I was using the fuction in nnUNet/nnunet/preprocessing/cropping.py.
The fuction "crop_to_nonzero" seems not working, I think it is using the original image to do the crop. 
"nonzero_mask = create_nonzero_mask(data)" . After croping image and mask, the size does not change.

**Comment by FabianIsensee** [comment] 2021-05-25 07:59
This is exactlythe intended behavior. This function is made for brain MRI where everything except the brain is 0. It does not do anything for other images

**Comment by Karol-G** [comment] 2023-07-31 14:08
Closing this issue as it seems solved. Feel free to open the issue again, if you have further questions.

**Closed by Karol-G** 2023-07-31 14:08 UTC
