### ISSUE TITLE
Using "all" for training, pseudo dice in training is too different from validation dice in validation. 

### ISSUE THREAD

**Issue by SherlockZYB** [MIC-DKFZ/nnUNet#1499] opened 2023-06-15 11:30 UTC
I use code "nnUNetv2_train ID 2d all --npz" to train my own dataset. And at epoch 299, I have three classes, and it's region-based classes, the 'WT' corresponds 1,2,3 in the original label, 'NC' corresponds 1, 'ET' corresponds 3, the result shows below:

![image](https://github.com/MIC-DKFZ/nnUNet/assets/55788145/25a965d4-28a9-4c54-82ac-53040fe5842b)

However, the validation dice is:

![image](https://github.com/MIC-DKFZ/nnUNet/assets/55788145/c28c19bc-cc11-4c3e-a5d0-4bf58d656400)

According to my understanding, when I use "all", training and validation will use the same dataset, and in validation, nnUNetv2 will use the final model (such as the epoch 299 model here, my epoch_num is 300). So I wonder why the same dataset, the same model,  will the result be so different?

**Comment by TaWald** [comment] 2023-08-09 08:16
Hey,

Firstly, it's correct that when you use the "all" flag instead of an id of a fold you use all the data for training and validation. Also it is correct that nnUNet uses the last checkpoint to do the final inference on your validation samples to create the mean validation dice.  
In general I would not recommend using the "all" flag as you cannot rely on the metrics on the validation set anymore as the model was trained on the same samples.  

### Differences between the metric calculation during training and validation:
1. During training the dice scores are calculated **across all batches** , which merges the scores of multiple samples. `nnunetv2/training/nnUNetTrainer/nnUNetTrainer.py` Line 964
2. During training you only calculate the score on the patches you cropped and not on the entire cases, which you do during the final validation, because you usually care about the entire case not only a patch from it. 
3. During training you sample foreground and background patches. When selecting foreground, a random pixel of your foreground is selected and the patch is center cropped around it. During validation you tile so the foreground class may lay at the border of the image, affecting performance. 

Getting to the root of your problem is difficult without knowing more about properties of segmentations, but if I had to guess, I would assume that point 1 is the culprit for you:
If your target structures is **only sometimes contained** in a case or if the **sizes of the targets vary greatly**, the batch evaluation would make a proper evaluation of it very difficult. E.g. you could have a case where you have the structure present get segmented perfectly, and a case where it isn't present / where the target is much smaller segmented very poorly. If you calculate the dice jointly the large segmentation dominates the Pseudo dice calculation and the other target basically does not affect the metric. Now in the final evaluation each case is treated seperately and you get one case that works nicely and one that poorly averaging to mean dice ~0.5. 

In order to actually see if your model has differing performance between training and validation, I would recommend that you check the `summary.json` in the folder where the validation predictions are created. It should contain the dice scores per case. This will give you a good indication if the described scenario above could apply to you.

If this is the case it would be nice if you let me know so I can close this issue, otherwise feel free to post an excerpt of the summary.json or provide some more information to get to the bottom of this.

Cheers

**Comment by TaWald** [comment] 2023-08-21 08:34
If you investigated a bit and found the root cause of this issue, it would be nice if you could report back @SherlockZYB otherwise I will close this issue due to inactivity

**Closed** 2023-09-01 06:14 UTC
Labels: good first issue
