### ISSUE TITLE
questions about numworkers

### ISSUE THREAD

**Issue by Hikaryyy** [MIC-DKFZ/nnUNet#1564] opened 2023-07-19 13:14 UTC
Hi，how can I adjust the numbur of num_workers？
I need to reduce the number of processes to ensure that my processes are not interrupted

**Comment by ancestor-mithril** [comment] 2023-07-19 13:17
For training, you can use an environment variable, `nnUNet_n_proc_DA`. 
For inference, planning and preprocessing, you can use `command -h` to find arguments which control the number of processes involved.

**Comment by TaWald** [comment] 2023-08-09 06:56
Hi @Hikaryyy 
did the previous answer solve your problem already?
If not please specify which nnUNet command you are running.

**Comment by Hikaryyy** [comment] 2023-08-11 02:09
nnUNetv2_predict -i ./dataset/nnUNet_raw/Dataset666_liver15/imagesTr_c2 -o ./dataset/nnUNet_raw/Dataset666_liver15/labelsTr -d 190 -c 3d_fullres -f 6   -chk checkpoint_best.pth
Hello, this is my running command
I have adopted all methods to minimize RAM as much as possible and avoid concurrent tasks. So that I can safely execute the prediction

**Comment by TaWald** [comment] 2023-08-11 08:00
If you check the arguments you can pass to `nnUNetv2_predict` [here](https://github.com/MIC-DKFZ/nnUNet/blob/5af388417c36b566ea029cc8b4e057d75a8ed422/nnunetv2/inference/predict_from_raw_data.py#L643), you can control the number of processes of preprocessing and segmentation export processes. Probably the preprocess processes are the issues for you. 

```python
   parser.add_argument('-npp', type=int, required=False, default=3,
                        help='Number of processes used for preprocessing. More is not always better. Beware of '
                             'out-of-RAM issues. Default: 3')
    parser.add_argument('-nps', type=int, required=False, default=3,
                        help='Number of processes used for segmentation export. More is not always better. Beware of '
                             'out-of-RAM issues. Default: 3')
```

lease set `-npp 1` and `-nps 1` to reduce your memory overhead (if this is an OOM problem).
Please start `htop` to monitor your RAM usage and then run 
`nnUNetv2_predict -i ./dataset/nnUNet_raw/Dataset666_liver15/imagesTr_c2 -o ./dataset/nnUNet_raw/Dataset666_liver15/labelsTr -d 190 -c 3d_fullres -f 6 -chk checkpoint_best.pth -npp 1 -nps 1`

Should your process abort due to another reason than OOM, add the `--verbose` flag and post the stack trace, as you clearly run into some other issue.

**Comment by Hikaryyy** [comment] 2023-08-14 06:22
now my running command  belike:
nnUNetv2_predict -i ./inputs_crop/1 -o ./out_15 -d 667 -c 3d_fullres -f 2 -npp 1 -nps 1  -chk checkpoint_best.pth
the inputs_path has only a [840 ,512 , 512] nii.gz file，but I find that when running the predict command，my computer's 64g ram are full. it looks  so crazy!

**Comment by Hikaryyy** [comment] 2023-08-14 06:23
> 如果选中可以传递[到此处](https://github.com/MIC-DKFZ/nnUNet/blob/5af388417c36b566ea029cc8b4e057d75a8ed422/nnunetv2/inference/predict_from_raw_data.py#L643)的参数，则可以控制预处理和分段导出进程的进程数。可能预处理过程是您的问题。`nnUNetv2_predict`
> 
> ```python
>    parser.add_argument('-npp', type=int, required=False, default=3,
>                         help='Number of processes used for preprocessing. More is not always better. Beware of '
>                              'out-of-RAM issues. Default: 3')
>     parser.add_argument('-nps', type=int, required=False, default=3,
>                         help='Number of processes used for segmentation export. More is not always better. Beware of '
>                              'out-of-RAM issues. Default: 3')
> ```
> 
> 租约集并减少内存开销（如果这是 OOM 问题）。请开始监控您的 RAM 使用情况，然后运行`-npp 1``-nps 1``htop` `nnUNetv2_predict -i ./dataset/nnUNet_raw/Dataset666_liver15/imagesTr_c2 -o ./dataset/nnUNet_raw/Dataset666_liver15/labelsTr -d 190 -c 3d_fullres -f 6 -chk checkpoint_best.pth -npp 1 -nps 1`
> 
> 如果进程由于 OOM 以外的其他原因而中止，请添加标志并发布堆栈跟踪，因为您显然会遇到其他问题。`--verbose`
现在我的运行命令是这样的：
nnUNetv2_predict -i ./inputs_crop/1 -o ./out_15 -d 667 -c 3d_fullres -f 2 -NPP 1 -nps 1 -chk checkpoint_best.pth
inputs_path只有一个 [840 ，512， 512] nii.gz 文件，但我发现在运行预测命令时，我的计算机的 64g 内存已满。看起来太疯狂了！

**Comment by Hikaryyy** [comment] 2023-08-14 06:26
> 如果选中可以传递[到此处](https://github.com/MIC-DKFZ/nnUNet/blob/5af388417c36b566ea029cc8b4e057d75a8ed422/nnunetv2/inference/predict_from_raw_data.py#L643)的参数，则可以控制预处理和分段导出进程的进程数。可能预处理过程是您的问题。`nnUNetv2_predict`
> 
> ```python
>    parser.add_argument('-npp', type=int, required=False, default=3,
>                         help='Number of processes used for preprocessing. More is not always better. Beware of '
>                              'out-of-RAM issues. Default: 3')
>     parser.add_argument('-nps', type=int, required=False, default=3,
>                         help='Number of processes used for segmentation export. More is not always better. Beware of '
>                              'out-of-RAM issues. Default: 3')
> ```
> 
> 租约集并减少内存开销（如果这是 OOM 问题）。请开始监控您的 RAM 使用情况，然后运行`-npp 1``-nps 1``htop` `nnUNetv2_predict -i ./dataset/nnUNet_raw/Dataset666_liver15/imagesTr_c2 -o ./dataset/nnUNet_raw/Dataset666_liver15/labelsTr -d 190 -c 3d_fullres -f 6 -chk checkpoint_best.pth -npp 1 -nps 1`
> 
> 如果进程由于 OOM 以外的其他原因而中止，请添加标志并发布堆栈跟踪，因为您显然会遇到其他问题。`--verbose`

now my command belike：
nnUNetv2_predict -i ./inputs_crop/1 -o ./out_15 -d 667 -c 3d_fullres -f 2 -NPP 1 -nps 1 -chk checkpoint_best.pth
my inpouts path has only a  [840 ，512， 512] nii.gz file.But I find that when running the predict command,my computer's 64g ram is full. It looks so crazy!

**Comment by TaWald** [comment] 2023-08-14 07:05
840x512x512 is quite a large case, which leads to a lot of softmax probabilities that have to be kept in memory. Do you by any chance predict a lot of output classes?

**Comment by Hikaryyy** [comment] 2023-08-14 07:15
> 840x512x512 is quite a large case, which leads to a lot of softmax probabilities that have to be kept in memory. Do you by any chance predict a lot of output classes?

Yes, there are 14 types here, excluding backgrounds

**Comment by Hikaryyy** [comment] 2023-08-15 01:06
> 840x512x512 is quite a large case, which leads to a lot of softmax probabilities that have to be kept in memory. Do you by any chance predict a lot of output classes?

I even crop it ：）

**Comment by TaWald** [comment] 2023-08-15 08:07
Just to make sure: Do you have multiple files in that directory? If so you may have to set the default num processes in your environment variables: 
`default_num_processes = 8 if 'nnUNet_def_n_proc' not in os.environ else int(os.environ['nnUNet_def_n_proc'])` 

You can check for them by (e.g.) activating your nnUNet environment, starting the python interpreter and print the os.environ variable:

1. `conda activate <YOUR_ENV_NAME` or for virtualenv `source <PATH_TO_ACTIVATE>`
2. `python`
```python
import os
os.getenv("nnUNet_def_n_proc", "None")
```
If its None you haven't defined it and nnUNet will use 8 processes. Then you should add this environment variable and set it to 1, to only use a single thread for the preprocessing.

**Comment by Hikaryyy** [comment] 2023-08-15 09:42
> Just to make sure: Do you have multiple files in that directory? If so you may have to set the default num processes in your environment variables: `default_num_processes = 8 if 'nnUNet_def_n_proc' not in os.environ else int(os.environ['nnUNet_def_n_proc'])`
> 
> You can check for them by (e.g.) activating your nnUNet environment, starting the python interpreter and print the os.environ variable:
> 
> 1. `conda activate <YOUR_ENV_NAME` or for virtualenv `source <PATH_TO_ACTIVATE>`
> 2. `python`
> 
> ```python
> import os
> os.getenv("nnUNet_def_n_proc", "None")
> ```
> 
> If its None you haven't defined it and nnUNet will use 8 processes. Then you should add this environment variable and set it to 1, to only use a single thread for the preprocessing.

Hey， can this method be used in predict？

**Comment by TaWald** [comment] 2023-08-15 09:49
I am not quite sure what you mean by that. This is just a way to check how many preprocessing processes you are actually running.
If you mean if you could inject the code snippet into the predict call somewhere then, yes. Doing so would print out the number of processes or "None" if you don't have it defined.

How exactly do you use nnUNet? Did you install it via `pip install nnunet` or did you clone the git repository?

**Comment by Hikaryyy** [comment] 2023-08-16 03:06
> I am not quite sure what you mean by that. This is just a way to check how many preprocessing processes you are actually running. If you mean if you could inject the code snippet into the predict call somewhere then, yes. Doing so would print out the number of processes or "None" if you don't have it defined.
> 
> How exactly do you use nnUNet? Did you install it via or did you clone the git repository? If you would post the exact commands you call **before running** it would probably help already so I can guide you through the process more easily.`pip install nnunet``nnUNetv2_predict`

What I  mean is that ：can this setting affect the prediction of nnUNet to prevent jamming during the prediction ？ After setting this environment variable “nnUNet_def_n_proc = 1”, the issue of my predict process getting stuck was not resolved.

**Comment by TaWald** [comment] 2023-08-16 08:48
>can this setting affect the prediction of nnUNet to prevent jamming during the prediction
This setting sets the number of processes that simultaneously do stuff during inference and it increases memory burden. Each of the workers would keep a preprocessed image in memory, thus increasing the memory demand.

As of right now it is really hard to guess the state of your machine and environment while you run since you do not answer my questions fully:
1.  Did you install it via `pip install nnunet` or did you use `git clone <repository_url>`?
2. Post the exact commands you call **before** running nnUNetv2_predict and the exact command **and the stack trace** (error message) (if you get one) as it would probably help already so I can guide you through the process more easily.
3. Post the output of `ls <YOUR_INPUT_PATH>` with that being the `-i` path you pass to nnunet_predict
4. Post the output of `echo $nnUNet_def_n_proc` 
 
Please don't only respond with stuff worked or not, but provide some more detailed info. **Optimally this would include providing a reproducible example** for me so I can work the stuff out.

**Comment by TaWald** [comment] 2023-08-21 08:37
Hey @Hikaryyy , did you follow through with the steps I provided you with?
Let me know if you need further clarification.

**Comment by Hikaryyy** [comment] 2023-08-22 01:23
> 嘿，你按照我给你提供的步骤了吗？如果您需要进一步澄清，请告诉我。

I have adopted your method, but my raw data is too large and it is still difficult to solve the problem of memory overflow. In the end, I used the method of shrinking and crop to reduce the data size to ensure smooth process

**Comment by TaWald** [comment] 2023-08-23 11:15
Not really a satisfying conclusion, since a lot of context information is lacking to provide a cleaner solution.
However since a lot of miscommunication is happening I will close this. Should someone run into a similar issue, please open a new issue.
Cheers

**Comment by bhatrana** [comment] 2023-10-04 15:27
@TaWald I have same issue, installed nnunet2 on windows. RAM of 48 GB and a GPU 
![image](https://github.com/MIC-DKFZ/nnUNet/assets/79718549/94aa9045-8406-4c89-9a6a-eb89c30ef4c4)

**Comment by TaWald** [comment] 2023-10-11 08:41
Thanks @bhatrana for the stack trace.
Seems like your matrix just has so many values to the 216 classes that you run OOM on your machine due to it.
Originally nnU-Net was not designed for dataset with so many classes, hence it's limitations on these large, high classes cases. I believe with the growing number of issues with this, we will look into how we can deal with this.

In the mean time you can probably reduce the floating point precision of the matrix manually, which will reduce memory footprint.

**Comment by bhatrana** [comment] 2023-10-12 18:08
Hi @TaWald  : Yes I sorted out, the labels on the provided segmentation were random, as nnUNet requires ascending order of labels. I relabeled provided labels in 20 classes starting with 1. Thank you for this nice work. Please close this issue.

**Comment by TaWald** [comment] 2023-10-14 17:48
Nice that you figured it out!

**Closed** 2023-10-14 17:48 UTC
Labels: enhancement
